# .github/workflows/xcode-tests.yml
name: Xcode Unit Tests

on:
  push:
    branches: [ main, feature/*, fix/* ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Build and test
        run: |
          xcodebuild \
            -scheme ComfyMark \
            -destination 'platform=macOS' \
            clean test
